Day03App/Controllers/DepartmentCoursesController.cs
using Day03App.Models;
using Day04App.Data;
using Day04App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Day04App.Controllers
{
    public class DepartmentCoursesController : Controller
    {
        private DatabaseITI _db;

        public DepartmentCoursesController(DatabaseITI db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            ViewBag.depts = new SelectList(_db.Departments.ToList(), "Id", "Name");
            return View();
        }

        public IActionResult GetCourses(int id)
        {
            Department dept = _db.Departments.Include(x=>x.CoursesInDept).FirstOrDefault(x => x.Id == id);

            List<Course> coursesInDept = dept.CoursesInDept;
            List<Course> coursesNotInDept = _db.Courses.ToList().Except(coursesInDept).ToList();

            DepartmentCourseViewModel model = new DepartmentCourseViewModel();
            model.CoursesInDept = coursesInDept;
            model.CoursesNotInDept = coursesNotInDept;
            model.Department = dept;

            return PartialView(model);
        }

        public IActionResult updateCourses(int[] coursesInDept, int[] coursesNotInDept, int id)
        {
            Department dept = _db.Departments.Include(x=>x.CoursesInDept).FirstOrDefault(x => x.Id == id);
            List<Course> coursesToRemove= new List<Course>();
            foreach (var item in coursesInDept)
            {
                coursesToRemove.Add(_db.Courses.FirstOrDefault(x => x.CrsID == item));
            }
            foreach (var item in coursesToRemove)
            {
                dept.CoursesInDept.Remove(item);
            }
            _db.SaveChanges();

            List<Course> coursesToAdd = new List<Course>();
            foreach (var item in coursesNotInDept)
            {
                coursesToAdd.Add(_db.Courses.FirstOrDefault(x => x.CrsID == item));
            }
            foreach (var item in coursesToAdd)
            {
                dept.CoursesInDept.Add(item);
            }
            _db.SaveChanges();


            return RedirectToAction("index");
        }
    }
}

Day03App/Controllers/StudentCoursesController.cs
using Day03App.Models;
using Day04App.Data;
using Day04App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Day04App.Controllers
{
    public class StudentCoursesController : Controller
    {
        private DatabaseITI _db;

        public StudentCoursesController(DatabaseITI db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            ViewBag.stds = new SelectList(_db.Students.ToList(), "Id", "Name");
            return View();
        }

        public IActionResult GetCourses(int id)
        {
            Student std = _db.Students.Include(x => x.Department).AsNoTracking().FirstOrDefault(s => s.Id == id);
            //Department stdDpt = _db.Departments.Include(x => x.CoursesInDept).AsNoTracking().FirstOrDefault(x => x.Id == std.DeptId);
            
            Student stdCrsToAdd = _db.Students.Include(x => x.StudentCourses).ThenInclude(x => x.Course).FirstOrDefault(x => x.Id == id);
            //stdCrsToAdd.StudentCourses.ToList().IntersectBy(std.Department.CoursesInDept.ToList(), x => x.CrsId);
            //stdCrsToAdd.StudentCourses.ToList().IntersectBy(std.Department.CoursesInDept.ToList(), x => x.CrsId);
            for (int i = 0; i < std.Department.CoursesInDept.Count; i++)
            {
                stdCrsToAdd.StudentCourses.Add(new StudentCourses { StdId = std.Id, CrsId = std.Department.CoursesInDept[i].CrsID });
            }
            stdCrsToAdd.StudentCourses = stdCrsToAdd.StudentCourses.DistinctBy(x => x.CrsId).ToList();

            List<StudentCourses> studentCoursesTemp = stdCrsToAdd.StudentCourses.ToList();

            //studentCoursesTemp.IntersectBy(stdDpt.)

            _db.SaveChanges();
            List<StudentCourses> stdCrs = _db.Students.Include(x => x.StudentCourses).ThenInclude(x => x.Course).AsNoTracking().FirstOrDefault(x => x.Id == id).StudentCourses;

            return PartialView(stdCrs);
        }

        public IActionResult setGrade(int[] crsIDs, int[] Degrees, int id)
        {
            if (crsIDs.Length == Degrees.Length)
            {
                for (int i = 0; i < crsIDs.Length; i++)
                {
                    _db.StudentCourses.FirstOrDefault(x => x.StdId == id && x.CrsId == crsIDs[i]).Degree = Degrees[i];
                }
                _db.SaveChanges();
            }
            return RedirectToAction("index");
        }
    }
}

Day03App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day03App.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="../Views/Shared/_Layout.cshtml.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">System Mangment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Search">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DepartmentCourses" asp-action="Index">DepartmentCourse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentCourses" asp-action="Index">StudentCourses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Day03App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>